insert into `compute-1-367804.sales.Customer` (customer_id, customer_name, location) values
(1,"John Doe", "London"),
(2,"Joe Lewis", "London"),
(3,"John Lewis", "London"),
(4,"Lewis Lewis", "Ipswich"),
(5,"Frank Tom Lewis", "Birmingham"),
(6,"Pete Frank", "Birmingham"),
(7,"Ken Dodds", "London"),
(8,"Freddie Smith", "Manchester"),
(9,"Jack Sawyer", "Liverpool"),
(10,"Brendan Phillips", "Liverpool"),
(11,"Theo Jakov Gold", "Manchester"),
(12,"Marcus Praeda", "Ipswich"),
(13,"Marcus Rashie", "Manchester"),
(14,"Stephen Solokov", "Ipswich"),
(15,"Freda Bell", "Liverpool"),
(16,"August May", "Ipswich"),
(17,"Brendan Manone", "London"),
(18,"Kenneth Branagh", "Manchester"),
(19,"Landon Donielle", "Birmingham"),
(20,"Jenny Cramer", "London")