models:
  - name: dim_product_full_data
#    config:
#      contract:
#        enforced: true
    columns:
      - name: product_name
        data_tests:
          - not_null
        constraints:
          - type: not_null
      - name: product_category
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['Regular','Luxury','Custom']
              severity: warn
  - name: dim_product_sentiment
    columns:
      - name: product_id
        data_tests:
          - not_null
      - name: product_name
        data_tests:
          - not_null
      - name: product_category
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: [ 'Regular','Luxury','Custom' ]
  - name: dim_customer
    columns:
      - name: customer_id
      - name: customer_full_name
      - name: first_name
      - name: last_name
      - name: location
        data_tests:
          - location_fixed



