version: 2

sources:
  - name: sales
    database: compute-1-367804
    tables:
      - name: Customer
      - name: Product
      - name: Sentiment
        config:
          loaded_at_field: date
          freshness:
            warn-after: {count: 365, period: day}
            error-after: {count: 500, period: day}
      - name: Sales
